-- HU-13.1 - Entidad SERVICE con su indice y sus restricciones.

CREATE TABLE SERVICE (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    COMPANY_ID      NUMBER         NOT NULL,
    CODIGO          VARCHAR2(30)   NOT NULL,
    NOMBRE          VARCHAR2(120)  NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    TARIFA          NUMBER(12,2)   NOT NULL,
    ACTIVO          NUMBER(1)      DEFAULT 1 NOT NULL,
    CREADO_EN       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN  TIMESTAMP,
    CONSTRAINT PK_SERVICE        PRIMARY KEY (ID),
    CONSTRAINT UK_SERVICE_CODIGO UNIQUE (COMPANY_ID, CODIGO),
    CONSTRAINT CK_SERVICE_TARIFA CHECK (TARIFA > 0),
    CONSTRAINT CK_SERVICE_ACTIVO CHECK (ACTIVO IN (0, 1))
);

-- COMPANY_ID va primero: es el filtro presente en todas las consultas.
CREATE INDEX IDX_SERVICE_COMPANY_ACTIVO ON SERVICE (COMPANY_ID, ACTIVO);

COMMENT ON TABLE  SERVICE IS 'Servicios tecnicos del catalogo, por empresa';
COMMENT ON COLUMN SERVICE.COMPANY_ID IS 'Referencia a DFX_USUARIOS.COMPANY. Sin FK: otro esquema';
COMMENT ON COLUMN SERVICE.ACTIVO IS 'Desactivacion logica: no se borra para no romper ordenes historicas';
