-- HU-17.1 - Entidad PART con el indice que sirve la consulta de bajo minimo.

CREATE TABLE PART (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    COMPANY_ID      NUMBER         NOT NULL,
    SKU             VARCHAR2(40)   NOT NULL,
    NOMBRE          VARCHAR2(120)  NOT NULL,
    STOCK           NUMBER(10)     DEFAULT 0 NOT NULL,
    STOCK_MINIMO    NUMBER(10)     DEFAULT 0 NOT NULL,
    COSTO_UNITARIO  NUMBER(12,2),
    ACTIVO          NUMBER(1)      DEFAULT 1 NOT NULL,
    CREADO_EN       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ACTUALIZADO_EN  TIMESTAMP,
    CONSTRAINT PK_PART          PRIMARY KEY (ID),
    CONSTRAINT UK_PART_SKU      UNIQUE (COMPANY_ID, SKU),
    CONSTRAINT CK_PART_STOCK    CHECK (STOCK >= 0),
    CONSTRAINT CK_PART_MINIMO   CHECK (STOCK_MINIMO >= 0),
    CONSTRAINT CK_PART_COSTO    CHECK (COSTO_UNITARIO IS NULL OR COSTO_UNITARIO >= 0),
    CONSTRAINT CK_PART_ACTIVO   CHECK (ACTIVO IN (0, 1))
);

CREATE INDEX IDX_PART_BAJO_MINIMO ON PART (COMPANY_ID, STOCK, STOCK_MINIMO);

COMMENT ON TABLE  PART IS 'Repuestos y su stock, por empresa';
COMMENT ON COLUMN PART.STOCK IS 'CK_PART_STOCK garantiza que nunca quede bajo cero';
